<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>e310a284-8619-47ef-9b85-b6f7a3f27c79</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Views\" />
    <Folder Include="wwwroot\css\" />
    <Folder Include="wwwroot\img\" />
    <Folder Include="wwwroot\js\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="FirebaseAdmin" Version="3.4.0" />
    <PackageReference Include="Google.Apis.Auth" Version="1.72.0" />
    <PackageReference Include="Google.Cloud.Firestore" Version="3.11.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Cookies" Version="2.3.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
